AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function ListBucketsCommand.
Parameters:
  FunctionName:
    Type: String
    Description: "Github branch name e.g. development"
  TemplateBucket:
    Type: String
    Default: ""

Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: lambda-test-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GithubToLambda:
    Type: AWS::Lambda::Function
    DependsOn: LambdaRole
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: nodejs22.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        S3Bucket: !Ref ${TemplateBucket}
        S3Key: !Sub /lambda-files/${FunctionName}.zip
      Description: List Amazon S3 buckets in us-east-1.
      TracingConfig:
        Mode: Active