AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function ListBucketsCommand.
Parameters:
  FunctionName:
    Type: String
    Description: "Github branch name e.g. development"
  TemplateBucket:
    Type: String
    Default: ""

Resources:
  FunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: function-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GithubToLambda:
    Type: AWS::Lambda::Function
    DependsOn: FunctionRole
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: nodejs22.x
      Role: !GetAtt FunctionRole.Arn
      Handler: index.handler 
      Code: ./dist/index.js
      Description: List Amazon S3 buckets in us-east-1.
      TracingConfig:
        Mode: Active