version: 0.2
phases:
  build:
    commands:
    - cd "${PROJECT_SUBFOLDER}"
      - echo "Executing ChangeSet..."
      - CHANGESET_NAME=$(cat changeset_env.txt)
      - aws cloudformation execute-change-set --stack-name $STACK_NAME --change-set-name $CHANGESET_NAME