version = 0.1

[2]
[2.global]
[2.global.parameters]
stack_name = "sam-prod"
s3_prefix = "sam-prod"
s3_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-fqukeaqujtkq"
region = "us-east-1"
image_repository = "774305613815.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-wfos6c0i2tew"

[2.deploy]
[2.deploy.parameters]
template = "template.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[1]
[1.global]
[1.global.parameters]
stack_name = "sam-testing"
s3_prefix = "sam-testing"
s3_bucket = "aws-sam-cli-managed-testing-pipeli-artifactsbucket-wypuaoxxkgil"
region = "us-east-1"
image_repository = "774305613815.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-testing-pipeline-resources-imagerepository-yvnegmqika2j"

[1.deploy]
[1.deploy.parameters]
template = "template.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "sam-pipeline"
s3_prefix = "sam-pipeline"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
