Description: Root Stack, contains all the resources needed for the application
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  nestedSkeletonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/fm-iac-artifact-bucket/templates/github-to-lambda.yaml
      Parameters:
        FunctionName: "github-to-lambda"
        TemplateBucket: "fm-iac-artifact-bucket"



