Description: Root Stack, contains all the resources needed for the application
AWSTemplateFormatVersion: '2010-09-09'

Resources:
# DynamoDB table stacks
  WeatherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WeatherTable
      AttributeDefinitions:
        - AttributeName: Location
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: Location
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Environment
          Value: Production
        - Key: Application
          Value: EcoWise
  # Lambda function stacks
  nestedSkeletonStack:
    Type: AWS::CloudFormation::Stack 
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/github-to-lambda.yaml
      Parameters:
        FunctionName: "github-to-lambda"
        TemplateBucket: "eco-wise-iac-artifact-bucket"
  nestedFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/github-to-lambda-02.yaml
      Parameters:
        FunctionName: "github-to-lambda-02"
        TemplateBucket: "eco-wise-iac-artifact-bucket"

  nestedFunctionThreeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/github-to-lambda-03.yaml
      Parameters:
        FunctionName: "github-to-lambda-03"
        TemplateBucket: "eco-wise-iac-artifact-bucket" 
  nestedFunctionFourStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/github-to-lambda-04.yaml
      Parameters:
        FunctionName: "github-to-lambda-04"
        TemplateBucket: "eco-wise-iac-artifact-bucket" 
  WeatherApiFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/weather-api-function.yaml
      Parameters:
        FunctionName: "weather-api-function"
        TemplateBucket: "eco-wise-iac-artifact-bucket" 

