Description: Root Stack, contains all the resources needed for the application
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  functionOne:
    Type: AWS::CloudFormation::Stack 
    Properties:
      TemplateURL: https://s3.amazonaws.com/eco-wise-iac-artifact-bucket/templates/github-to-lambda.yaml
      Parameters:
        FunctionName: "function-01"
        TemplateBucket: "eco-wise-iac-artifact-bucket"



